### ISSUE TITLE
Consider adding Web Games to SeaORM showcase!

### ISSUE THREAD

**Issue by billy1624** [u4ium/web-games#1]
Hey @u4ium, feel free to submit a PR to showcase your project!
- https://github.com/SeaQL/sea-orm/issues/403

**Comment by u4ium** [comment]
I love SeaORM and will certainly do so when I have a more impressive project to showcase using it. 

Keep up the good work!

**Comment by billy1624** [comment]
Thanks!! @u4ium :D
